klarnaUsername: ${KLARNA_USERNAME:PK39673_c191181dff0c}
klarnaPassword: ${KLARNA_PASSWORD:vkBYCqyByafqL2dZ}
klarnaBaseUrl: https://api.playground.klarna.com/
klarnaCheckoutPath: /checkout/v3/orders

server:
  port: 80
logging:
  level:
    root: INFO
    org.springframework.web: INFO